### PR TITLE
Introduce TracingStatefulRedisCLusterConnection

### PR DESCRIPTION
**Pull request by fujigon**
Introduce TracingStatefulRedisCLusterConnection as wrapper for lettuce's cluster connection.

### CODE REVIEW

**Comment by fujigon** [comment]
I'd like to add test cases for TracingStatefulRedisClusterConnection same as https://github.com/opentracing-contrib/java-redis-client/blob/master/opentracing-redis-lettuce/src/test/java/io/opentracing/contrib/redis/lettuce/TracingLettuceTest.java#L60.

Can redis on `localhost` behave as redis cluster?

**Comment by malafeev** [comment]
I'm not sure that `RedisServer` which is used in tests can be used in cluster mode. But let's try.

**Comment by fujigon** [comment]
https://github.com/kstyrc/embedded-redis/tree/master/src/main/resources
disappointingly, the embedded-redis encloses and uses redis v2.8.19, which doesn't have cluster feature.

I found a fork of the embedded-redis, which support redis-culuster
https://github.com/fmonniot/embedded-redis#setting-up-a-cluster, but it doesn't enclose redis, and forces us to install redis-server locally.

**Comment by fujigon** [comment]
https://github.com/fujigon/java-redis-client/pull/1/files
here's my attempt... 😇

**Comment by malafeev** [comment]
I would like to avoid installing locally redis

**Comment by fujigon** [comment]
thanks for merging!
I'd like to use this feature and test in my side.
Could you kindly release new version including this please?

**Comment by malafeev** [comment]
version `0.1.2` just released.
should be available in maven central soon.
please make sure that your tracer is based in latest opentracing api `0.32.0` (it was released couple of weeks ago)

**Comment by fujigon** [comment]
thanks for releasing and advice.
I'll try it :)

**Pull request merged**
